# Generated by Django 3.2.6 on 2021-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namirnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('ugljikohidrati', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('masnoca', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('proteini', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kalorije', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelacijaTablaNamirnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namirnica', models.ManyToManyField(to='Kalkulator.Namirnica')),
                ('tablica', models.ManyToManyField(blank=True, to='Kalkulator.Tabla')),
            ],
        ),
    ]
